tap "jesseduffield/lazygit"
brew "bat"
brew "broot"
brew "chezmoi"
brew "difftastic"
brew "eza"
brew "fd"
brew "fzf"
brew "jq"
brew "neovim"
brew "parallel"
brew "ripgrep"
brew "starship"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "jesseduffield/lazygit/lazygit"

# Casks (GUI applications)
cask "karabiner-elements"
cask "obsidian"
