import { actionLayer } from "./rules.ts";
import { LayerCommand, LayerKeySublayer, StickySubLayer } from "./utils.ts";

type SubLayerValue = LayerCommand | LayerKeySublayer | StickySubLayer;

function isCommand(v: SubLayerValue): v is LayerCommand {
  return "to" in v;
}

function isSticky(v: SubLayerValue): v is StickySubLayer {
  return "sticky" in v;
}

/** Human-readable summary of what a command does, for the cheat-sheet. */
function describe(cmd: LayerCommand): string {
  if (cmd.description) return cmd.description;
  const to = cmd.to?.[0];
  if (!to) return "(no-op)";
  if (to.key_code) {
    const mods = to.modifiers?.length ? `${to.modifiers.join(" + ")} + ` : "";
    return `\`${mods}${to.key_code}\``;
  }
  if (to.consumer_key_code) return `\`${to.consumer_key_code}\` (consumer)`;
  if (to.shell_command) return `\`${to.shell_command}\``;
  if (to.software_function?.open_application) {
    const o = to.software_function.open_application;
    if (o.frontmost_application_history_index !== undefined) {
      return `previous app (history ${o.frontmost_application_history_index})`;
    }
    return `open ${o.file_path ?? o.bundle_identifier}`;
  }
  if (to.set_variable) {
    return `set \`${to.set_variable.name}\` = ${to.set_variable.value}`;
  }
  return "(command)";
}

function subLayerLines(sub: LayerKeySublayer): string {
  return Object.entries(sub)
    .map(([key, cmd]) => `  - \`${key}\` → ${describe(cmd!)}`)
    .join("\n");
}

const directLines: string[] = [];
const sublayerBlocks: string[] = [];
const stickyBlocks: string[] = [];

for (const [key, value] of Object.entries(actionLayer)) {
  if (isSticky(value)) {
    stickyBlocks.push(`- **\`${key}\`**\n${subLayerLines(value.sticky)}`);
  } else if (isCommand(value)) {
    directLines.push(`- \`${key}\` → ${describe(value)}`);
  } else {
    sublayerBlocks.push(`- **\`${key}\`**\n${subLayerLines(value)}`);
  }
}

const readme = `# Keymap

> **Generated by \`deno task docs\` — do not edit by hand.** Edit \`rules.ts\` and
> re-run \`deno task docs\`. See \`README.md\` for setup and how the layers work.

**Right Command** is the action-layer key: hold it and press a key below. Tapping
Right Command alone sends Escape.

**Caps Lock** sends Escape when tapped and acts as Left Control when held. While a
sticky sublayer is active, Caps Lock cancels it instead.

## Direct mappings — Right Command + key

${directLines.join("\n")}

## Sublayers — Right Command + key, then a sub-key (active while held)

${sublayerBlocks.join("\n\n")}

## Sticky sublayers — tap to latch until the next key press

${stickyBlocks.join("\n\n")}
`;

const outFile = Deno.args[0] ?? "KEYMAP.md";
await Deno.writeTextFile(outFile, readme);
